SELECT * FROM XX1
SELECT * FROM XX0

UPDATE XX0
SET 
    XX0_PORTA = 6800,
    XX0_IP = '127.0.0.1'
WHERE XX0_ENV = 'OFICIAL';


-- update XX0 set XX0_IP = '127.0.0.1', XX0_PORTA = 6800 where XX0_ENV = 'AMBIENTE_ATUAL'

-- update XX0 set XX0_ENV = 'AMBIENTE_NOVO' where XX0_ENV = 'AMBIENTE_ANTIGO'

-- update XX1 set XX1_ENV = 'AMBIENTE_NOVO' where XX1_ENV = 'AMBIENTE_ANTIGO'

-- UPDATE XX1
-- SET 
    -- XX1_ENV = 'CCODE_TCLOUD'
-- WHERE XX1_ENV = 'OFICIAL';


-- UPDATE XX0
-- SET 
-- XX0_ENV = 'EMPRESA_DEV'
-- WHERE 
-- XX0_ENV = 'EMPRESA'
-- AND XX0_ENV <> 'EMPRESA_DEV';

SELECT * FROM XX1
SELECT * FROM XX0