---TSS_DE_NOTA-http://tss-homologacao.totvscloud.com.br:8261
---TSS_DO_TAF-http://taf-hmg.tss.cloudtotvs.com.br:8080
---ALIAS_DO_CLIENTE
---URL_EXTERNA_DO_WF
---URL_INTERNA_DO_WF

---ATUALIZA AS URLS DO TSS DE NOTA FISCAL ELETRÔNICA E DE SERVIÇO
UPDATE SX6010
SET 
    X6_CONTEUD = 'http://tss-homologacao.totvscloud.com.br:8261',
    X6_CONTSPA = 'http://tss-homologacao.totvscloud.com.br:8261',
    X6_CONTENG = 'http://tss-homologacao.totvscloud.com.br:8261'
WHERE X6_VAR = 'MV_SPEDURL';

---ATUALIZA AS URLS DO TSS DE NOTA FISCAL DE CUPOM ELETRÔNICO
UPDATE SX6010
SET 
    X6_CONTEUD = 'http://tss-homologacao.totvscloud.com.br:8261',
    X6_CONTSPA = 'http://tss-homologacao.totvscloud.com.br:8261',
    X6_CONTENG = 'http://tss-homologacao.totvscloud.com.br:8261'
WHERE X6_VAR = 'MV_NFCEURL';

---ATUALIZA AS URLS DO TSS DO TAF PARA TRANSMISSÃO DO E-SOCIAL E REINF
UPDATE SX6010
SET 
    X6_CONTEUD = 'http://taf-hmg.tss.cloudtotvs.com.br:8080',
    X6_CONTSPA = 'http://taf-hmg.tss.cloudtotvs.com.br:8080',
    X6_CONTENG = 'http://taf-hmg.tss.cloudtotvs.com.br:8080'
WHERE X6_VAR = 'MV_TAFSURL';

---ATUALIZA PARA A PORTA PADRÃO 7891 DO DBACCESS PARA A ROTINA DE AUTOCONTIDAS DO TAF.
UPDATE SX6010
SET 
    X6_CONTEUD = 7891,
    X6_CONTSPA = 7891,
    X6_CONTENG = 7891
WHERE X6_VAR = 'MV_TAFPORT';

---ATUALIZA O NOME DO BANCO DE DADOS UTILIZADO NO TAF
UPDATE SX6010
SET 
    X6_CONTEUD = 'ALIAS_DO_CLIENTE',
    X6_CONTSPA = 'ALIAS_DO_CLIENTE',
    X6_CONTENG = 'ALIAS_DO_CLIENTE'
WHERE X6_VAR = 'MV_TAFTALI';

---ATUALIZA O ENDEREÇO EXTERNO DO WORKFLOW
UPDATE SX6010
SET 
    X6_CONTEUD = 'URL_EXTERNA_DO_WF',
    X6_CONTSPA = 'URL_EXTERNA_DO_WF',
    X6_CONTENG = 'URL_EXTERNA_DO_WF'
WHERE X6_VAR = 'MV_WFHTTPE';

---ATUALIZA O ENDEREÇO INTERNO DO WORKFLOW
UPDATE SX6010
SET 
    X6_CONTEUD = 'URL_INTERNA_DO_WF',
    X6_CONTSPA = 'URL_INTERNA_DO_WF',
    X6_CONTENG = 'URL_INTERNA_DO_WF'
WHERE X6_VAR = 'MV_WFHTTPI';

---SELECT PARA EXIBIR AS ALTERAÇÕES NA TABELA APÓS OS UPDATES:
SELECT X6_CONTEUD, X6_CONTSPA, X6_CONTENG
FROM SX6010
WHERE X6_VAR IN ('MV_SPEDURL', 'MV_NFCEURL', 'MV_TAFSURL', 'MV_TAFPORT', 'MV_TAFTALI', 'MV_TAFREST', 'MV_BACKEND', 'MV_GCTPURL', 'ZZ_WFIPEXT', 'ZZ_WFQHOST', 'MV_WFBRWSR', 'MV_WFHTTPE', 'MV_WFHTTPI', 'MV_NGWFHT');