-- SELECT PARA EXIBIR AS ALTERAÇÕES NA TABELA APÓS OS UPDATES:
SELECT X6_VAR, X6_CONTEUD, X6_CONTSPA, X6_CONTENG
FROM SX6
WHERE X6_VAR IN ('MV_SPEDURL', 'MV_NFCEURL', 'MV_TAFSURL', 'MV_TAFPORT', 'MV_TAFTALI', 'MV_TAFREST', 'MV_BACKEND', 'MV_GCTPURL', 'ZZ_WFIPEXT', 'ZZ_WFQHOST', 'MV_WFBRWSR', 'MV_WFHTTPE', 'MV_WFHTTPI', 'MV_NGWFHT');

-- SELECT PARA EXIBIR AS ALTERAÇÕES NA TABELA APÓS OS UPDATES:
SELECT X6_VAR, X6_CONTEUD, X6_CONTSPA, X6_CONTENG
FROM SX6010
WHERE X6_VAR IN ('MV_SPEDURL', 'MV_NFCEURL', 'MV_TAFSURL', 'MV_TAFPORT', 'MV_TAFTALI', 'MV_TAFREST', 'MV_BACKEND', 'MV_GCTPURL', 'ZZ_WFIPEXT', 'ZZ_WFQHOST', 'MV_WFBRWSR', 'MV_WFHTTPE', 'MV_WFHTTPI', 'MV_NGWFHT');

-- SELECT PARA EXIBIR AS ALTERAÇÕES NA TABELA APÓS OS UPDATES:
SELECT X6_VAR, X6_CONTEUD, X6_CONTSPA, X6_CONTENG
FROM SX6010_BKP
WHERE X6_VAR IN ('MV_SPEDURL', 'MV_NFCEURL', 'MV_TAFSURL', 'MV_TAFPORT', 'MV_TAFTALI', 'MV_TAFREST', 'MV_BACKEND', 'MV_GCTPURL', 'ZZ_WFIPEXT', 'ZZ_WFQHOST', 'MV_WFBRWSR', 'MV_WFHTTPE', 'MV_WFHTTPI', 'MV_NGWFHT');


-- SELECT PARA EXIBIR AS ALTERAÇÕES NA TABELA APÓS OS UPDATES:
SELECT X6_VAR, X6_CONTEUD, X6_CONTSPA, X6_CONTENG
FROM SX6X3101
WHERE X6_VAR IN ('MV_SPEDURL', 'MV_NFCEURL', 'MV_TAFSURL', 'MV_TAFPORT', 'MV_TAFTALI', 'MV_TAFREST', 'MV_BACKEND', 'MV_GCTPURL', 'ZZ_WFIPEXT', 'ZZ_WFQHOST', 'MV_WFBRWSR', 'MV_WFHTTPE', 'MV_WFHTTPI', 'MV_NGWFHT');